_security:
    resource: "@AlphaLemonCmsBundle/Resources/config/routing/security.xml"

_pages:
    resource: "@AlphaLemonCmsBundle/Resources/config/routing/pages.xml"

_languages:
    resource: "@AlphaLemonCmsBundle/Resources/config/routing/languages.xml"

_theme_preview:
    resource: "@AlphaLemonCmsBundle/Resources/config/routing/theme-preview.xml"

_themes:
    resource: "@AlphaLemonCmsBundle/Resources/config/routing/themes.xml"

_blocks:
    resource: "@AlphaLemonCmsBundle/Resources/config/routing/blocks.xml"

_json_block:
    resource: "@AlphaLemonCmsBundle/Resources/config/routing/json-block.xml"

_deploy:
    resource: "@AlphaLemonCmsBundle/Resources/config/routing/deploy.xml"

_al_elfinder:
    resource: "@AlphaLemonCmsBundle/Resources/config/routing/elfinder.xml"

_navigation1:
  pattern:  /backend/{page}
  defaults: { _controller: AlphaLemonCmsBundle:AlCms:show, page: index }

_navigation:
  pattern:  /backend/{_locale}/{page}
  defaults: { _controller: AlphaLemonCmsBundle:AlCms:show, _locale: en, page: index }

_home:
  pattern:  /backend
  defaults: { _controller: AlphaLemonCmsBundle:AlCms:show, _locale: en, page: index }
