security:
    firewalls:
        login:
            pattern:  ^/backend/login$
            security: false

        alphalemon_cms:
            pattern:    ^/backend
            form_login:
                check_path:  /backend/login_check
                login_path:  /backend/login
            logout:
                path:   /backend/logout
                target: /backend/

    providers:
        custom_provider:
            id: alphalemon.cms.security.provider

    encoders:
        AlphaLemon\AlphaLemonCmsBundle\Core\Security\Proxy\AlUser: sha512

    access_control:
        ## The routes used by AlphaLemon CMS
        #
        # - { path: ^/backend/[a-z]+/al_showPages, roles: ROLE_USER }
        # - { path: ^/backend/[a-z]+/al_savePage, role: ROLE_USER }
        # - { path: ^/backend/[a-z]+/al_deletePage, role: ROLE_USER }
        # - { path: ^/backend/[a-z]+/al_loadPageAttributes, role: ROLE_USER }
        # - { path: ^/backend/[a-z]+/al_showBlocksEditor, role: ROLE_USER }
        # - { path: ^/backend/[a-z]+/addBlock, role: ROLE_USER }
        # - { path: ^/backend/[a-z]+/editBlock, role: ROLE_USER }
        # - { path: ^/backend/[a-z]+/deleteBlock, role: ROLE_USER }
        # - { path: ^/backend/[a-z]+/showExternalFilesManager, role: ROLE_USER }
        # - { path: ^/backend/[a-z]+/removeExternalFile, role: ROLE_USER }
        # - { path: ^/backend/[a-z]+/al_showFilesManager, role: ROLE_USER }
        # - { path: ^/backend/[a-z]+/al_elFinderMediaConnect, role: ROLE_USER }
        # - { path: ^/backend/[a-z]+/al_elFinderStylesheetsConnect, role: ROLE_USER }
        # - { path: ^/backend/[a-z]+/al_elFinderJavascriptsConnect, role: ROLE_USER }
        # - { path: ^/backend/[a-z]+/al_showLanguages, role: ROLE_USER }
        # - { path: ^/backend/[a-z]+/al_saveLanguage, role: ROLE_USER }
        # - { path: ^/backend/[a-z]+/al_deleteLanguage, role: ROLE_USER }
        # - { path: ^/backend/[a-z]+/al_loadLanguageAttributes, role: ROLE_USER }
        # - { path: ^/backend/[a-z]+/al_uploadFile, role: ROLE_USER }
        # - { path: ^/backend/[a-z]+/al_showThemes, role: ROLE_USER }
        # - { path: ^/backend/[a-z]+/al_importTheme, role: ROLE_USER }
        # - { path: ^/backend/[a-z]+/al_activateTheme, role: ROLE_USER }
        # - { path: ^/backend/[a-z]+/al_extractTheme, role: ROLE_USER }
        # - { path: ^/backend/[a-z]+/al_removeTheme, role: ROLE_USER }
        # - { path: ^/backend/[a-z]+/al_installAssets, role: ROLE_USER }
        # - { path: ^/backend/users/[a-z]+/al_userList, role: ROLE_ADMIN }
        # - { path: ^/backend/users/[a-z]+/al_showUser, role: ROLE_ADMIN }
        # - { path: ^/backend/users/[a-z]+/al_saveUser, role: ROLE_ADMIN }
        # - { path: ^/backend/users/[a-z]+/al_deleteUser, role: ROLE_ADMIN }
        # - { path: ^/backend/users/[a-z]+/al_rolesList, role: ROLE_ADMIN }
        # - { path: ^/backend/users/[a-z]+/al_showRole, role: ROLE_ADMIN }
        # - { path: ^/backend/users/[a-z]+/al_saveRole, role: ROLE_ADMIN }
        # - { path: ^/backend/users/[a-z]+/al_deleteRole, role: ROLE_ADMIN }

        - { path: ^/backend/[a-z]+/al_deploy, role: ROLE_ADMIN }
        - { path: ^/backend/users, roles: ROLE_ADMIN }
        - { path: ^/backend, roles: ROLE_USER }

    role_hierarchy:
        ROLE_ADMIN:         ROLE_USER
        ROLE_SUPER_ADMIN:   [ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]
