security:
    encoders:
        AlphaLemon\AlphaLemonCmsBundle\Model\AlUser:
            algorithm: sha512
            #encode_as_base64: true
            #iterations: 5000

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        main:
          propel:
              class: AlphaLemon\AlphaLemonCmsBundle\Model\AlUser
              property: username

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        alphalemon_login:
            pattern:  ^/backend/login$
            security: false

        alphalemon:
            pattern:    ^/backend
            form_login:
                check_path:  /backend/login_check
                login_path:  /backend/login
            logout:
                path:   /backend/logout
                target: /backend/login
            http_basic: ~
            context: primary_auth

    access_control:
        - { path: "^/backend/[a-z]+/al_(stage|production)Deploy", role: ROLE_ADMIN }
        - { path: ^/backend/users, roles: ROLE_ADMIN }
        - { path: ^/backend, roles: ROLE_USER }
