AlphaLemon\AlphaLemonCmsBundle\Model\AlUser:
  properties:
    username:
      - NotBlank: { message: Username field can not be empty }
      - MinLength: { limit: 3, message: Username field is too short. It should have 3 characters or more  }
    password:
      - NotBlank: { message: Password field can not be empty }
      - MinLength: { limit: 6, message: Password field is too short. It should have 6 characters or more  }
    email:
      - NotBlank: { message: Email field can not be empty }
      - Email: { message: The email you entered is not valid  }
      
AlphaLemon\AlphaLemonCmsBundle\Model\AlRole:
  properties:
    role:
      - NotBlank: { message: Role field can not be empty }
      - Regex: { pattern: "/^ROLE_[\w+]/", message: A valid role must start with the ROLE_ prefix  } 